from __future__ import annotations

import json
import subprocess
from datetime import datetime
from pathlib import Path

from .config import Config
from .drafts import load_site


HEADER = """\
/* GENERATED by evergreenlabs-bot. Edit data/site/*.json in the bot repo, then `bot publish`.
   Schema: see the website's original siteData.js header for field-by-field comments.
   HTML-bearing fields (now.text, log[].body, project.writeup) are rendered with
   dangerouslySetInnerHTML; treat this file as trusted input. */

export const SITE = {payload};
"""


def render_sitedata_js(site: dict) -> str:
    site_ordered = {
        "profile": site.get("profile", {}),
        "now": site.get("now", {}),
        "projects": site.get("projects", []),
        "contributions": site.get(
            "contributions",
            {"totalContributions": 0, "fetchedAt": None, "weeks": []},
        ),
        "roadmap": site.get("roadmap", []),
        "log": site.get("log", []),
    }
    payload = json.dumps(site_ordered, indent=2, ensure_ascii=False)
    return HEADER.format(payload=payload)


def publish(cfg: Config) -> Path:
    site = load_site()
    target = cfg.website_sitedata_path
    target.parent.mkdir(parents=True, exist_ok=True)
    contents = render_sitedata_js(site)
    target.write_text(contents)

    if cfg.publish_git_commit:
        _git_commit(cfg, target)
    if cfg.publish_git_push:
        _git_push(cfg)
    return target


def _git_commit(cfg: Config, target: Path) -> None:
    rel = target.relative_to(cfg.website_repo_path)
    # Stage just the generated file.
    subprocess.run(
        ["git", "add", str(rel)],
        cwd=cfg.website_repo_path,
        check=True,
    )
    # Skip empty commits.
    diff = subprocess.run(
        ["git", "diff", "--cached", "--quiet"],
        cwd=cfg.website_repo_path,
    )
    if diff.returncode == 0:
        return
    msg = f"content: regenerate siteData.js ({datetime.utcnow().date().isoformat()})"
    subprocess.run(
        ["git", "commit", "-m", msg],
        cwd=cfg.website_repo_path,
        check=True,
    )


def _git_push(cfg: Config) -> None:
    subprocess.run(["git", "push"], cwd=cfg.website_repo_path, check=True)
