// GitHub Contents API publish helper. Replaces the `subprocess.run(["git", ...])`
// dance from src/evergreenlabs_bot/publish.py — Workers has no FS, no git.
//
// Wire format mirrors publish.py.render_sitedata_js() so successive publishes
// (Python -> TS during migration, then TS -> TS) produce diff-clean commits:
//
//   /* GENERATED by evergreenlabs-bot. Edit data/site/*.json in the bot repo,
//      then `bot publish`.
//      Schema: see the website's original siteData.js header for field-by-field
//      comments.
//      HTML-bearing fields (now.text, log[].body, project.writeup) are rendered
//      with dangerouslySetInnerHTML; treat this file as trusted input. */
//
//   export const SITE = { ... };
//
// We do NOT use the literal `const siteData = ...;` prefix mentioned in some
// places — publish.py is the source of truth and uses `export const SITE`.

import { ghFetch, type GhAppEnv } from "./github";

const HEADER = `/* GENERATED by evergreenlabs-bot. Edit data/site/*.json in the bot repo, then \`bot publish\`.
   Schema: see the website's original siteData.js header for field-by-field comments.
   HTML-bearing fields (now.text, log[].body, project.writeup) are rendered with
   dangerouslySetInnerHTML; treat this file as trusted input. */

export const SITE = `;

const FOOTER = ";\n";

export interface PublishEnv extends GhAppEnv {
  WEBSITE_REPO_OWNER: string;
  WEBSITE_REPO_NAME: string;
  SITE_DATA_PATH: string;
}

interface ContentsResponse {
  sha: string;
  content: string;
  encoding: string;
  path: string;
}

/** Render the canonical siteData.js text for the given parsed object. */
export function renderSiteData(site: Record<string, unknown>): string {
  // Preserve the canonical key order from publish.py.render_sitedata_js so
  // commits stay diff-clean across Python/TS publishes. Unknown keys (e.g.
  // _tracer in Slice 1) are appended after the known set, sorted.
  const orderedKeys = [
    "profile",
    "now",
    "projects",
    "contributions",
    "roadmap",
    "log",
  ];
  const out: Record<string, unknown> = {};
  for (const k of orderedKeys) {
    if (k === "contributions") {
      out[k] = site[k] ?? { totalContributions: 0, fetchedAt: null, weeks: [] };
    } else if (k === "profile" || k === "now") {
      out[k] = site[k] ?? {};
    } else {
      out[k] = site[k] ?? [];
    }
  }
  const extraKeys = Object.keys(site)
    .filter((k) => !orderedKeys.includes(k))
    .sort();
  for (const k of extraKeys) out[k] = site[k];

  return HEADER + JSON.stringify(out, null, 2) + FOOTER;
}

/**
 * Extract the JSON object payload from an existing siteData.js. Works for
 * both the Python `export const SITE = {...};` shape and the legacy
 * `const siteData = {...};` shape — we just find the first `{` and the
 * last `}`. Throws if no JSON object is present.
 */
export function parseSiteData(text: string): Record<string, unknown> {
  const firstBrace = text.indexOf("{");
  const lastBrace = text.lastIndexOf("}");
  if (firstBrace < 0 || lastBrace < firstBrace) {
    throw new Error("publish: existing siteData.js has no JSON object");
  }
  const json = text.slice(firstBrace, lastBrace + 1);
  return JSON.parse(json) as Record<string, unknown>;
}

function decodeBase64Content(b64: string): string {
  // GitHub returns base64 with line breaks every 60 chars.
  const stripped = b64.replace(/\s+/g, "");
  const bin = atob(stripped);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}

function encodeContentBase64(text: string): string {
  const bytes = new TextEncoder().encode(text);
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}

function deepMerge(
  base: Record<string, unknown>,
  patch: Record<string, unknown>,
): Record<string, unknown> {
  const out: Record<string, unknown> = { ...base };
  for (const [k, v] of Object.entries(patch)) {
    const existing = out[k];
    if (
      v !== null &&
      typeof v === "object" &&
      !Array.isArray(v) &&
      existing !== null &&
      typeof existing === "object" &&
      !Array.isArray(existing)
    ) {
      out[k] = deepMerge(
        existing as Record<string, unknown>,
        v as Record<string, unknown>,
      );
    } else {
      out[k] = v;
    }
  }
  return out;
}

async function readSiteData(
  env: PublishEnv,
): Promise<{ text: string; sha: string }> {
  const res = await ghFetch(
    env,
    `/repos/${env.WEBSITE_REPO_OWNER}/${env.WEBSITE_REPO_NAME}/contents/${env.SITE_DATA_PATH}`,
  );
  if (!res.ok) {
    throw new Error(
      `publish: GET contents failed ${res.status} ${await res.text()}`,
    );
  }
  const body = (await res.json()) as ContentsResponse;
  return { text: decodeBase64Content(body.content), sha: body.sha };
}

async function writeSiteData(
  env: PublishEnv,
  text: string,
  sha: string,
  message: string,
): Promise<Response> {
  return ghFetch(
    env,
    `/repos/${env.WEBSITE_REPO_OWNER}/${env.WEBSITE_REPO_NAME}/contents/${env.SITE_DATA_PATH}`,
    {
      method: "PUT",
      body: JSON.stringify({
        message,
        content: encodeContentBase64(text),
        sha,
      }),
    },
  );
}

/**
 * Deep-merge `partial` into the current siteData.js, render, and PUT.
 *
 * `kind` is folded into the commit message so reviewing the site repo's
 * history surfaces which Workflow caused each publish.
 *
 * Retries once on 409 (sha conflict) by re-fetching and re-merging.
 */
export async function publishSiteData(
  env: PublishEnv,
  partial: Record<string, unknown>,
  kind: string,
): Promise<void> {
  for (let attempt = 0; attempt < 2; attempt++) {
    const { text, sha } = await readSiteData(env);
    const parsed = parseSiteData(text);
    const merged = deepMerge(parsed, partial);
    const newText = renderSiteData(merged);
    if (newText === text) return; // idempotent, no-op publish
    const message = `chore(bot): ${kind} @ ${new Date().toISOString()}`;
    const res = await writeSiteData(env, newText, sha, message);
    if (res.ok) return;
    if (res.status === 409 && attempt === 0) continue; // retry once
    throw new Error(`publish: PUT failed ${res.status} ${await res.text()}`);
  }
}
