import { describe, it, expect } from "vitest";
import { renderSiteData, parseSiteData } from "./publish";

describe("renderSiteData / parseSiteData round-trip", () => {
  it("round-trips a full site object", () => {
    const input = {
      profile: { name: "Sam" },
      now: { weekOf: "may 24", text: "building things" },
      projects: [{ slug: "foo", title: "Foo" }],
      contributions: { totalContributions: 42, fetchedAt: null, weeks: [] },
      roadmap: [{ id: "1", title: "Ship it" }],
      log: [{ date: "may 24", year: "2026", body: "did stuff", project: "foo" }],
    };
    const rendered = renderSiteData(input);
    const parsed = parseSiteData(rendered);
    expect(parsed).toEqual(input);
  });

  it("fills defaults for missing keys", () => {
    const rendered = renderSiteData({});
    const parsed = parseSiteData(rendered);
    expect(parsed.profile).toEqual({});
    expect(parsed.now).toEqual({});
    expect(parsed.projects).toEqual([]);
    expect(parsed.contributions).toEqual({ totalContributions: 0, fetchedAt: null, weeks: [] });
    expect(parsed.roadmap).toEqual([]);
    expect(parsed.log).toEqual([]);
  });

  it("preserves canonical key order", () => {
    const rendered = renderSiteData({ log: [], profile: {} });
    const keys = Object.keys(parseSiteData(rendered));
    const expected = ["profile", "now", "projects", "contributions", "roadmap", "log"];
    expect(keys).toEqual(expected);
  });

  it("appends extra keys after canonical keys, sorted", () => {
    const rendered = renderSiteData({ zebra: 1, alpha: 2 });
    const keys = Object.keys(parseSiteData(rendered));
    expect(keys.slice(-2)).toEqual(["alpha", "zebra"]);
  });

  it("includes the GENERATED header and export const SITE", () => {
    const rendered = renderSiteData({});
    expect(rendered).toContain("GENERATED by evergreenlabs-bot");
    expect(rendered).toContain("export const SITE = ");
  });
});

describe("parseSiteData", () => {
  it("throws on text with no JSON object", () => {
    expect(() => parseSiteData("no json here")).toThrow("no JSON object");
  });

  it("parses legacy const siteData format", () => {
    const legacy = 'const siteData = {"profile":{"name":"Sam"}};\n';
    const parsed = parseSiteData(legacy);
    expect(parsed.profile).toEqual({ name: "Sam" });
  });
});
